version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5433:5432"
    networks:
      - app
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app:
    driver: bridge

volumes:
  pgdata:
